# API Configuration
openai_api_key: "your-openai-api-key"
azure_openai_api_key: "your-azure-openai-api-key"
azure_openai_endpoint: "https://your-azure-openai-endpoint.openai.azure.com/"

# File Paths
text_folder: "./texts"
database_path: "./vectordb.sqlite"

# API URL
backend_api_url: "http://localhost:8000"

# Vector Embedding
embedding_model: "text-embedding-ada-002"
chunk_size: 1000
chunk_overlap: 200

# SQLite Vector Search
distance_function: "cosine"
top_k: 5

#Llama 3.1
local_ollama_embeddings_api_url: http://localhost:11434/api/embeddings
local_ollama_chat_api_url: http://localhost:11434/api/chat
local_ollama_model: llama3.1
