# API Configuration
openai_api_key: "your-openai-api-key"
azure_openai_api_key: "your-azure-openai-api-key"
azure_openai_endpoint: "https://your-azure-openai-endpoint.openai.azure.com/"

# File Paths
text_folder: "./texts"
database_path: "vectordb.sqlite"

# API URL
backend_api_url: "http://localhost:8000"

# Vector Embedding
embedding_model: "text-embedding-ada-002"
chunk_size: 300
chunk_overlap: 20

# SQLite Vector Search
distance_function: "cosine"
top_k: 5

# AI Service Configuration
ai_service: ollama  # Options: 'ollama', 'azure_openai', 'openai'
use_langchain: true  # Set to true to use LangChain-based implementations

# Ollama configuration
ollama_model: "llama3.1"

# Azure OpenAI configuration
azure_openai_api_key: "your_api_key"
azure_openai_endpoint: "https://your-resource-name.openai.azure.com/"
azure_openai_embedding_deployment: "your_embedding_deployment_name"
azure_openai_completion_deployment: "your_completion_deployment_name"

# Logging Configuration
logging:
  enabled: true
  level: INFO  # Can be DEBUG, INFO, WARNING, ERROR, CRITICAL
